# @package _global_
dataset:
  coeff: 10.0

model:
  bt:
    optimizer:
      learning_rate: 0.01
    batch_size: 128
    num_layer: 2
    seq_hidden_units: 16
    hr_size: 8
    fc_hidden_units: 4
    dropout_rate: 0.1
    num_heads: 1

  self_positional_encoding:
    max_relative_position: 15


exp:
  max_epochs: 50
