# @package _global_
dataset:
  max_number: 3000

model:
  bt:
    optimizer:
      learning_rate: 0.001
    batch_size: 32
    seq_hidden_units: 48
    hr_size: 88
    fc_hidden_units: 44
    dropout_rate: 0.1
    num_layer: 1
    num_heads: 3

    self_positional_encoding:
      max_relative_position: 15

exp:
  max_epochs: 100