# @package _global_
model:
  bt:
    tune_hparams: True
    hparams_grid:
      num_layer:
        - 1
      num_heads:
        - 2
        - 3
      learning_rate:
        - 0.001
        - 0.0001
      batch_size:
        - 32
        - 64
      seq_hidden_units:
        - 0.5
        - 1.0
      hr_size:
        - 0.5
        - 1.0
        - 2.0
      fc_hidden_units:
        - 0.5
        - 1.0
        - 2.0
      dropout_rate:
        - 0.1
        - 0.2
    resources_per_trial:
      cpu: 0.4
      gpu: 0.5

exp.seed: 100
