# @package _global_
dataset:
  coeff: 10.0

model:
  encoder:
    optimizer:
      learning_rate: 0.001
    batch_size: 64
    seq_hidden_units: 18
    br_size: 12
    fc_hidden_units: 24
    dropout_rate: 0.2
    num_layer: 1

  train_decoder: True
  decoder:
    optimizer:
      learning_rate: 0.01
    batch_size: 256
    br_size: 3
    fc_hidden_units: 6
    dropout_rate: 0.1
    num_layer: 2
    seq_hidden_units: 12

exp:
  weights_ema: False
  balancing: grad_reverse
  max_epochs: 50