# @package _global_
dataset:
  max_number: 3000

model:
  propensity_treatment:
    seq_hidden_units: 6                 # rnn_hidden_units in the original terminology
    dropout_rate: 0.2
    num_layer: 2
    batch_size: 128
    max_grad_norm: 2
    optimizer:
      learning_rate: 0.01

  propensity_history:
    seq_hidden_units: 148 #74                  # rnn_hidden_units in the original terminology
    dropout_rate: 0.2
    num_layer: 1
    batch_size: 64
    max_grad_norm: 2.0
    optimizer:
      learning_rate: 0.01

  encoder:
    seq_hidden_units: 148                  # rnn_hidden_units in the original terminology
    dropout_rate: 0.1                       # Dropout of LSTM hidden layers + output layers
    num_layer: 1
    batch_size: 128
    max_grad_norm: 2.0
    optimizer:
      learning_rate: 0.01

  train_decoder: True
  decoder:
    seq_hidden_units: 196                  # rnn_hidden_units in the original terminology
    dropout_rate: 0.2                       # Dropout of LSTM hidden layers + output layers
    num_layer: 1
    batch_size: 1024
    max_grad_norm: 2.0
    optimizer:
      learning_rate: 0.001

exp:
  max_epochs: 100