# @package _global_
dataset:
  coeff: 10.0

model:
  multi:
    optimizer:
      learning_rate: 0.01
    batch_size: 64
    seq_hidden_units: 16
    br_size: 4
    fc_hidden_units: 16
    dropout_rate: 0.2
    num_heads: 1
    num_layer: 1


  self_positional_encoding:
    max_relative_position: 15

exp:
  weights_ema: True
  alpha: 0.01
  beta: 0.99
  balancing: domain_confusion
  max_epochs: 50