# @package _global_
dataset:
  max_number: 3000

model:
  multi:
    optimizer:
      learning_rate: 0.001
    batch_size: 32
    seq_hidden_units: 90
    br_size: 88
    fc_hidden_units: 44
    dropout_rate: 0.2
    num_layer: 2
    num_heads: 3

    self_positional_encoding:
      max_relative_position: 15

exp:
  weights_ema: True
  alpha: 0.01
  beta: 0.99
  balancing: domain_confusion
  max_epochs: 100